threshold.systolic.low=90
threshold.systolic.high=140

threshold.diastolic.low=60
threshold.diastolic.high=90

threshold.pulse.low=55
threshold.pulse.high=100

threshold.temperature.low=36.0
threshold.temperature.high=37.5

threshold.glucose.low=3.9
threshold.glucose.high=10.0

threshold.oxygen.low=95
threshold.oxygen.high=100